<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MsContractor.NotificationService-15e7d315-8ab6-4394-85d4-87033de4c68a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MsContractor.Contracts\MsContractor.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\MsContractor.BuildingBlocks\MsContractor.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
