<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MsContractor.CatalogSyncService-b2843b9d-5201-43c8-9bd2-440e138dc307</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\MsContractor.Contracts\MsContractor.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared\MsContractor.BuildingBlocks\MsContractor.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
