// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsContractor.CatalogSyncService.Repo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsContractor.CatalogSyncService.Repo.Migrations
{
    [DbContext(typeof(CatalogSyncDbContext))]
    partial class CatalogSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog_sync")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.Counterparty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Inn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Kpp")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LastSyncRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("MoySkladUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedInn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NormalizedKpp")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Id")
                        .IsUnique();

                    b.HasIndex("LastSyncRunId", "AccountId");

                    b.HasIndex("AccountId", "NormalizedEmail");

                    b.HasIndex("AccountId", "NormalizedInn");

                    b.HasIndex("AccountId", "NormalizedName");

                    b.HasIndex("AccountId", "NormalizedPhone");

                    b.ToTable("counterparties", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("inbox_messages", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.MergeJob", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AccountId").HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CorrelationId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("MainCounterpartyId").HasColumnType("uuid");
                    b.Property<Guid>("MessageId").HasColumnType("uuid");
                    b.Property<string>("Payload").IsRequired().HasColumnType("jsonb");
                    b.Property<int>("PayloadVersion").HasColumnType("integer");
                    b.Property<Guid>("RequestedByUserId").HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasAlternateKey("Id", "AccountId");
                    b.HasIndex("MessageId").IsUnique();
                    b.HasIndex("AccountId", "CreatedAt");
                    b.HasIndex("AccountId", "Status");
                    b.ToTable("merge_jobs", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.MergeOperation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("AccountId").HasColumnType("uuid");
                    b.Property<int>("AttemptCount").HasColumnType("integer");
                    b.Property<DateTimeOffset?>("CompletedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("CounterpartyId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ErrorCode").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("ErrorMessage").HasMaxLength(512).HasColumnType("character varying(512)");
                    b.Property<Guid>("MergeJobId").HasColumnType("uuid");
                    b.Property<string>("OperationType").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int>("Sequence").HasColumnType("integer");
                    b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("MergeJobId", "AccountId");
                    b.HasIndex("MergeJobId", "OperationType", "CounterpartyId").IsUnique();
                    b.HasIndex("MergeJobId", "Sequence").IsUnique();
                    b.ToTable("merge_operations", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.SyncOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt", "CreatedAt");

                    b.ToTable("outbox_messages", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WindowFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WindowTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "AccountId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("AccountId", "CreatedAt");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("sync_runs", "catalog_sync");
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.Counterparty", b =>
                {
                    b.HasOne("MsContractor.CatalogSyncService.Repo.SyncRun", "LastSyncRun")
                        .WithMany("Counterparties")
                        .HasForeignKey("LastSyncRunId", "AccountId")
                        .HasPrincipalKey("Id", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.MergeOperation", b =>
                {
                    b.HasOne("MsContractor.CatalogSyncService.Repo.MergeJob", "MergeJob")
                        .WithMany("Operations")
                        .HasForeignKey("MergeJobId", "AccountId")
                        .HasPrincipalKey("Id", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MsContractor.CatalogSyncService.Repo.SyncWatermark", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastSyncRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Watermark")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountId");

                    b.ToTable("sync_watermarks", "catalog_sync");
                });
#pragma warning restore 612, 618
        }
    }
}
