FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

ARG PROJECT_PATH

RUN dotnet restore "$PROJECT_PATH"

RUN dotnet publish "$PROJECT_PATH" \
    -c Release \
    -o /app/publish \
    --no-restore \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

COPY --from=build /app/publish .

ARG PROJECT_DLL
ENV PROJECT_DLL=$PROJECT_DLL

ENTRYPOINT ["sh", "-c", "dotnet \"$PROJECT_DLL\""]