// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsContractor.VendorService.Repo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsContractor.VendorService.Repo.Migrations
{
    [DbContext(typeof(VendorDbContext))]
    [Migration("20260725192108_CreateVendorSchema")]
    partial class CreateVendorSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vendor")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsContractor.VendorService.Repo.Installation", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<JsonDocument>("AccessScope")
                        .HasColumnType("jsonb")
                        .HasColumnName("access_scope");

                    b.Property<byte[]>("AccessTokenCiphertext")
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_ciphertext");

                    b.Property<byte[]>("AccessTokenNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_nonce");

                    b.Property<byte[]>("AccessTokenTag")
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_tag");

                    b.Property<string>("AccountName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("account_name");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uuid")
                        .HasColumnName("app_id");

                    b.Property<string>("AppUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("app_uid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<DateTimeOffset?>("LastContextAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_context_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<JsonDocument>("Subscription")
                        .HasColumnType("jsonb")
                        .HasColumnName("subscription");

                    b.Property<int?>("TokenKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("token_key_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("pk_installations");

                    b.HasIndex("AppId")
                        .HasDatabaseName("ix_installations_app_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_installations_status");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_installations_updated_at");

                    b.ToTable("installations", "vendor");
                });

            modelBuilder.Entity("MsContractor.VendorService.Repo.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("PublishAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_outbox_messages_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("PublishedAt", "CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_unpublished");

                    b.ToTable("outbox_messages", "vendor");
                });

            modelBuilder.Entity("MsContractor.VendorService.Repo.OutboxMessage", b =>
                {
                    b.HasOne("MsContractor.VendorService.Repo.Installation", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_installation");
                });
#pragma warning restore 612, 618
        }
    }
}
