// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsContractor.MoySkladEgressService.Models;
using MsContractor.MoySkladEgressService.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsContractor.MoySkladEgressService.Persistence.Migrations
{
    [DbContext(typeof(EgressDbContext))]
    partial class EgressDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("egress")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.FactureInRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "DocumentId");

                b.ToTable("facturein_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.FactureInRecreationItem", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SourceFactureInId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<Guid>("MainCounterpartyId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("NewFactureInId")
                    .HasColumnType("uuid");

                b.Property<Guid>("NewSyncId")
                    .HasColumnType("uuid");

                b.Property<string>("PayloadJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<Guid?>("SourceSyncId")
                    .HasColumnType("uuid");

                b.Property<string>("Stage")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("AccountId", "SourceFactureInId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.FactureInRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "SourceFactureInId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.ToTable("facturein_recreation_items", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "DocumentId");

                b.ToTable("purchasereturn_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnPositionRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PositionId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PurchaseReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "PurchaseReturnId", "PositionId");

                b.HasIndex("AccountId", "PurchaseReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "PurchaseReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("purchasereturn_positions_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnFactureOutRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PurchaseReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "PurchaseReturnId", "DocumentId");

                b.HasIndex("AccountId", "PurchaseReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "PurchaseReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("purchasereturn_factureout_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnFactureInRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PurchaseReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "PurchaseReturnId", "DocumentId");

                b.HasIndex("AccountId", "PurchaseReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "PurchaseReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("purchasereturn_facturein_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnPaymentInRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PurchaseReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("OperationsBeforeJson")
                    .HasColumnType("jsonb");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<decimal?>("LinkedSum")
                    .HasColumnType("numeric");

                b.HasKey("AccountId", "PurchaseReturnId", "DocumentId");

                b.HasIndex("AccountId", "PurchaseReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "PurchaseReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("purchasereturn_paymentin_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PurchaseReturnCashInRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PurchaseReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("OperationsBeforeJson")
                    .HasColumnType("jsonb");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<decimal?>("LinkedSum")
                    .HasColumnType("numeric");

                b.HasKey("AccountId", "PurchaseReturnId", "DocumentId");

                b.HasIndex("AccountId", "PurchaseReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.PurchaseReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "PurchaseReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("purchasereturn_cashin_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.HasKey("AccountId", "DocumentId");

                b.ToTable("salesreturn_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnPositionRawData", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("PositionId")
                    .HasColumnType("uuid");

                b.Property<string>("RawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<Guid>("SalesReturnId")
                    .HasColumnType("uuid");

                b.HasKey("AccountId", "SalesReturnId", "PositionId");

                b.HasIndex("AccountId", "SalesReturnId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "SalesReturnId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("salesreturn_positions_raw_data", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnRecreationOperation", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("MainAgentId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("AccountId", "OperationId");

                b.ToTable("salesreturn_recreation_operations", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnRecreationItem", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SourceDocumentId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("DemandId")
                    .HasColumnType("uuid");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<Guid?>("NewDocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("NewPayloadJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<Guid>("NewSyncId")
                    .HasColumnType("uuid");

                b.Property<string>("SourceRawJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<string>("Stage")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RelationsStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid?>("TargetAgentAccountId")
                    .HasColumnType("uuid");

                b.HasKey("AccountId", "OperationId", "SourceDocumentId");

                b.HasIndex("AccountId", "OperationId");

                b.HasIndex("AccountId", "SourceDocumentId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRecreationOperation", null)
                    .WithMany("Items")
                    .HasForeignKey("AccountId", "OperationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRawData", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "SourceDocumentId")
                    .HasPrincipalKey("AccountId", "DocumentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.ToTable("salesreturn_recreation_items", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnRelationsSnapshotRecord", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<Guid>("SourceSalesReturnId")
                    .HasColumnType("uuid");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("AccountId", "OperationId", "SourceSalesReturnId");

                b.HasIndex("AccountId", "OperationId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRecreationItem", null)
                    .WithMany()
                    .HasForeignKey("AccountId", "OperationId", "SourceSalesReturnId")
                    .HasPrincipalKey("AccountId", "OperationId", "SourceDocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("salesreturn_relation_snapshots", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.PaymentOutRelationSnapshotRecord", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("DetachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<decimal>("LinkedSum")
                    .HasColumnType("numeric");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<string>("OperationsBeforeJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<string>("ReattachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("SourceSalesReturnId")
                    .HasColumnType("uuid");

                b.HasKey("AccountId", "OperationId", "SourceSalesReturnId", "DocumentId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRelationsSnapshotRecord", null)
                    .WithMany("PaymentOuts")
                    .HasForeignKey("AccountId", "OperationId", "SourceSalesReturnId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("salesreturn_paymentout_relations", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.CashOutRelationSnapshotRecord", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("DetachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<decimal>("LinkedSum")
                    .HasColumnType("numeric");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<string>("OperationsBeforeJson")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<string>("ReattachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<Guid>("SourceSalesReturnId")
                    .HasColumnType("uuid");

                b.HasKey("AccountId", "OperationId", "SourceSalesReturnId", "DocumentId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRelationsSnapshotRecord", null)
                    .WithMany("CashOuts")
                    .HasForeignKey("AccountId", "OperationId", "SourceSalesReturnId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("salesreturn_cashout_relations", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.LossRelationSnapshotRecord", b =>
            {
                b.Property<Guid>("AccountId")
                    .HasColumnType("uuid");

                b.Property<Guid>("DocumentId")
                    .HasColumnType("uuid");

                b.Property<string>("DetachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Error")
                    .HasColumnType("text");

                b.Property<string>("ErrorCode")
                    .HasColumnType("text");

                b.Property<Guid>("OperationId")
                    .HasColumnType("uuid");

                b.Property<string>("ReattachStatus")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("SalesReturnBeforeJson")
                    .HasColumnType("jsonb");

                b.Property<Guid>("SourceSalesReturnId")
                    .HasColumnType("uuid");

                b.HasKey("AccountId", "OperationId", "SourceSalesReturnId", "DocumentId");

                b.HasOne("MsContractor.MoySkladEgressService.Models.SalesReturnRelationsSnapshotRecord", null)
                    .WithMany("Losses")
                    .HasForeignKey("AccountId", "OperationId", "SourceSalesReturnId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.ToTable("salesreturn_loss_relations", "egress");
            });

            modelBuilder.Entity("MsContractor.MoySkladEgressService.Models.SalesReturnRelationsSnapshotRecord", b =>
            {
                b.Navigation("CashOuts");
                b.Navigation("Losses");
                b.Navigation("PaymentOuts");
            });

#pragma warning restore 612, 618
        }
    }
}
