@MsContractor_MoySkladEgressService_HostAddress = http://localhost:8082
@internalApiKey = HLgIyekmoPVyJUFAVv6U5XUsmxcQM8XwpmJvxS9EKSU=
@accountId = b3d34ec3-243f-11f1-0a80-0b21000042b5
@mainAgentId = 74c9e1a0-b422-11f1-0a80-13b0006be074
@salesReturnId = f975fd33-b422-11f1-0a80-1af400285a04

### Recreate salesreturns for the main counterparty from saved Egress raw data.
POST {{MsContractor_MoySkladEgressService_HostAddress}}/internal/accounts/{{accountId}}/documents/salesreturn/recreate
X-Internal-Api-Key: {{internalApiKey}}
Content-Type: application/json

{
  "mainAgentId": "{{mainAgentId}}",
  "salesReturnIds": [
    "{{salesReturnId}}", 
    "f00f6c93-b422-11f1-0a80-16730028d1eb"
  ]
}
