@MsContractor_MoySkladEgressService_HostAddress = http://localhost:8082
@internalApiKey = HLgIyekmoPVyJUFAVv6U5XUsmxcQM8XwpmJvxS9EKSU=
@accountId = b3d34ec3-243f-11f1-0a80-0b21000042b5
@mainCounterpartyId = 349dc7aa-b4f8-11f1-0a80-02d3003686ab
@purchaseReturnId = eb91a86d-b4e6-11f1-0a80-1b9e00a18492,

### Prepare purchasereturn documents for recreation.
POST {{MsContractor_MoySkladEgressService_HostAddress}}/internal/accounts/{{accountId}}/documents/purchasereturn/recreate
X-Internal-Api-Key: {{internalApiKey}}
Content-Type: application/json

{
  "mainCounterpartyId": "{{mainCounterpartyId}}",
  "purchaseReturnIds": [
    "{{purchaseReturnId}}"
  ]
}
